# Generated by Django 5.1.6 on 2025-03-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
