# Generated by Django 5.1.6 on 2025-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Sous-titre')),
                ('history_title', models.CharField(default='Notre Histoire', max_length=100, verbose_name='Titre Histoire')),
                ('history_content', models.TextField(verbose_name='Contenu Histoire')),
                ('mission_title', models.CharField(default='Notre Mission', max_length=100, verbose_name='Titre Mission')),
                ('mission_content', models.TextField(verbose_name='Contenu Mission')),
                ('process_title', models.CharField(default='Notre Processus de Sélection', max_length=100, verbose_name='Titre Processus')),
                ('team_title', models.CharField(default='Notre Équipe', max_length=100, verbose_name='Titre Équipe')),
                ('team_intro', models.TextField(verbose_name='Introduction Équipe')),
                ('cta_title', models.CharField(max_length=200, verbose_name='Titre CTA')),
                ('cta_content', models.TextField(verbose_name='Contenu CTA')),
            ],
            options={
                'verbose_name': 'Contenu À propos',
                'verbose_name_plural': 'Contenus À propos',
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(help_text='ex: fa-handshake', max_length=50, verbose_name='Icône Font Awesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Valeur de l'entreprise",
                'verbose_name_plural': "Valeurs de l'entreprise",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Étapes du processus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('position', models.CharField(max_length=100, verbose_name='Poste')),
                ('bio', models.TextField(verbose_name='Biographie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': "Membre de l'équipe",
                'verbose_name_plural': "Membres de l'équipe",
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('title', models.CharField(max_length=100, verbose_name='Titre/Métier')),
                ('location', models.CharField(max_length=100, verbose_name='Lieu')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-created_at'],
            },
        ),
    ]
