# Generated by Django 5.1.6 on 2025-02-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('delivery', 'Paiement à la livraison')], max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
