# Generated by Django 5.1.6 on 2025-04-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_image',
        ),
    ]
