# Generated by Django 5.1.6 on 2025-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
