# Generated by Django 5.1.6 on 2025-02-15 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('type', models.CharField(choices=[('order', 'Commande'), ('stock', 'Stock'), ('system', 'Système')], max_length=20, verbose_name='Type')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Niveau')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('action_url', models.CharField(blank=True, max_length=255, null=True, verbose_name="URL d'action")),
                ('icon', models.CharField(default='fas fa-bell', max_length=50, verbose_name='Icône')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('notifications', models.ManyToManyField(related_name='groups', to='notifications.notification', verbose_name='Notifications')),
            ],
            options={
                'verbose_name': 'Groupe de notifications',
                'verbose_name_plural': 'Groupes de notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['type', 'is_read'], name='notificatio_type_5ae648_idx'),
        ),
    ]
